# Generated by Django 3.1.6 on 2021-02-21 21:06

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210221_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='product'),
        ),
    ]
