# Generated by Django 3.1.6 on 2021-02-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'consumer', 'verbose_name_plural': 'consumers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'order product', 'verbose_name_plural': 'order products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'provider', 'verbose_name_plural': 'providers'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
