# Generated by Django 3.1.6 on 2021-02-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210214_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'aisle',
                'verbose_name_plural': 'aisles',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='aisle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.aisle'),
        ),
    ]
