# Generated by Django 3.1.7 on 2021-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210316_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'recommendation', 'verbose_name_plural': 'recommendations'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='common_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
