# Generated by Django 3.1.7 on 2021-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_orderproduct__price_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='_price_multiple',
            field=models.DecimalField(db_column='price_multiple', decimal_places=2, default=0, max_digits=99),
        ),
    ]
