# Generated by Django 3.1.7 on 2021-03-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210301_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'UserRating', 'verbose_name_plural': 'UserRatings'},
        ),
        migrations.AlterField(
            model_name='userrating',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
    ]
