# Generated by Django 3.2 on 2021-04-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20210418_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
