# Generated by Django 3.1.7 on 2021-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20210301_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'store', 'verbose_name_plural': 'store'},
        ),
    ]
