# Generated by Django 3.1.7 on 2021-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20210302_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='common_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
