# Generated by Django 3.2 on 2021-05-09 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0015_auto_20210508_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='id пользователя')),
                ('item_id', models.IntegerField(verbose_name='id продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения рекомендации')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'профиль клиента', 'verbose_name_plural': 'профили клиентов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.userprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
