# Generated by Django 3.2 on 2021-05-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20210510_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
