# Generated by Django 3.1.7 on 2021-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('pending', 'Подготовка заказа'), ('finished', 'Завершенный заказ'), ('canceled', 'Отмененный заказ')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
