# Generated by Django 3.2 on 2021-05-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_rename_recommendations_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата получения рекомендации'),
        ),
    ]
