# Generated by Django 3.2 on 2021-05-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_recommendation_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user_id', 'item_id')},
        ),
    ]
