# Generated by Django 3.1.7 on 2021-03-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20210310_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
